---
name: Testing

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          sudo apt-get install -y pcregrep
          pcregrep --help
