---
name: Testing

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - name: Test
        run: |
          apt update
          apt-get install -y pcregrep
          pcregrep --help
